// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDD-NZx0bF3X8Ar3JJ7W0Jc2as-pr3ahHM',
    appId: '1:848086921941:web:85949114b6b1f0e46d685c',
    messagingSenderId: '848086921941',
    projectId: 'casinopeoplecount',
    authDomain: 'casinopeoplecount.firebaseapp.com',
    storageBucket: 'casinopeoplecount.firebasestorage.app',
    measurementId: 'G-6ZHCQC7TWG',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyDN5o7YN7ZMa9OlzGnmMQePQotRp82wnfY',
    appId: '1:848086921941:android:c0d79d5759c2eb4e6d685c',
    messagingSenderId: '848086921941',
    projectId: 'casinopeoplecount',
    storageBucket: 'casinopeoplecount.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyBPFmUyLH7nGZzhtYMXeFD1hfOc9HCrtQU',
    appId: '1:848086921941:ios:df3e785c6c1dcee66d685c',
    messagingSenderId: '848086921941',
    projectId: 'casinopeoplecount',
    storageBucket: 'casinopeoplecount.firebasestorage.app',
    iosBundleId: 'com.example.casinoPeopleCocunt',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyBPFmUyLH7nGZzhtYMXeFD1hfOc9HCrtQU',
    appId: '1:848086921941:ios:df3e785c6c1dcee66d685c',
    messagingSenderId: '848086921941',
    projectId: 'casinopeoplecount',
    storageBucket: 'casinopeoplecount.firebasestorage.app',
    iosBundleId: 'com.example.casinoPeopleCocunt',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDD-NZx0bF3X8Ar3JJ7W0Jc2as-pr3ahHM',
    appId: '1:848086921941:web:ea733ff47bef3a706d685c',
    messagingSenderId: '848086921941',
    projectId: 'casinopeoplecount',
    authDomain: 'casinopeoplecount.firebaseapp.com',
    storageBucket: 'casinopeoplecount.firebasestorage.app',
    measurementId: 'G-KMDHS07BBH',
  );
}
